name: simlingo_upgrade_py310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - jupyter
  - ipython
  - ipykernel
  - gh
  - pip:
    - accelerate
    - adal
    - aiohttp
    - aiosignal
    - annotated-types
    - ansicolors
    - antlr4-python3-runtime
    - anyio
    - appdirs
    - async-timeout
    - asyncio-atexit
    - attrs
    - azure-common
    - azure-core
    - azure-identity
    - azure-keyvault
    - azure-keyvault-certificates
    - azure-keyvault-keys
    - azure-keyvault-secrets
    - azure-nspkg
    - azure-storage-blob
    - carla
    - certifi
    - cffi
    - charset-normalizer
    - click
    - cloudpickle
    - colorama
    - cramjam
    - cryptography
    - cycler
    - debugpy
    - deepdiff
    - deepspeed
    - dictor
    - distro
    - docker-pycreds
    - einops
    - elementpath
    - ephem
    - exceptiongroup
    - fastjsonschema
    - fastparquet
    - filelock
    - filterpy
    - fonttools
    - frozenlist
    - fsspec
    - gitdb
    - gitpython
    - gym
    - gym-notices
    - h11
    - h5py
    - hjson
    - httpcore
    - httpx
    - huggingface-hub
    - hydra-core
    - hydra-zen
    - idna
    - imageio
    - imaug # update
    - immutabledict
    - importlib-metadata
    - importlib-resources
    - isodate
    - jinja2
    - jiter
    - joblib
    - jsonschema
    - jsonschema-specifications
    - kiwisolver
    - laspy
    - laszip
    - lazrs
    - lazy-loader
    - lightning
    - lightning-utilities
    - line-profiler
    - lxml
    - markupsafe
    - matplotlib
    - mpmath
    - msal
    - msal-extensions
    - msgpack
    - msrest
    - msrestazure
    - multidict
    - nbclient
    - nbformat
    - networkx
    - ninja
    - numpy
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-ml-py
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - oauthlib
    - omegaconf
    - onnx
    - openai
    - opencv-python
    - ordered-set
    - orjson
    - packaging
    - pandas
    - papermill
    - peft
    - pexpect
    - pillow
    - pkgutil-resolve-name
    - portalocker
    - protobuf
    - psutil
    - py
    - py-cpuinfo
    - py-trees==0.8.3
    - pyarrow
    - pycparser
    - pydantic
    - pydantic-core
    - pydot
    - pygame
    - pyjwt
    - pynvml
    - pyparsing
    - python-dateutil
    - python-json-logger
    - pytorch-lightning
    - pytz
    - pywavelets
    - pyyaml
    - rdp
    - referencing
    - regex
    - requests
    - requests-oauthlib
    - retry
    - rpds-py
    - safetensors
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - send2trash
    - sentry-sdk
    - setproctitle
    - shapely
    - simple-watchdog-timer
    - smmap
    - sniffio
    - sympy
    - tabulate
    - tenacity
    - termcolor
    - threadpoolctl
    - tifffile
    - timm
    - tokenizers
    - torch
    - torchaudio
    - torchdata
    - torchmetrics
    - torchvision
    - tqdm
    - transformers
    - transforms3d
    - triton
    - typing-extensions
    - tzdata
    - ujson
    - urllib3
    - wandb
    - webcolors
    - xmlschema
    - yarl
    - zipp
